### ISSUE TITLE
l2proc crashes

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#1]
The level-2 processor crashes with the following error message: 

```
Traceback (most recent call last):
  File "bin/pysiral-l2proc.py", line 296, in <module>
    pysiral_l2proc()
  File "bin/pysiral-l2proc.py", line 37, in pysiral_l2proc
    pysiral_l2proc_time_range_job(args)
  File "bin/pysiral-l2proc.py", line 55, in pysiral_l2proc_time_range_job
    args.l2_output, overwrite_protection=args.overwrite_protection)
  File "bin/pysiral-l2proc.py", line 278, in l2_output
    l2_output_ids = self.pysiral_config.get_setting_ids("outputdef")
  File ".../pysiral/pysiral/config.py", line 116, in get_setting_ids
    ids, files = self.get_yaml_setting_filelist(lookup_directory)
  File ".../pysiral/pysiral/config.py", line 161, in get_yaml_setting_filelist
    if os.path.split(root)[-1] == "obsolete" and ignore_obsolete:
  File "/usr/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by shendric** [comment]
Fix in d236e76
