### ISSUE TITLE
Merged Snow Climatology auxiliary handler crashes for non-winter month

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#19]
**Describe the bug**
Merged snow climatology class crashes for month outside the winter period

**To Reproduce**
- run Level-2 processor with awi cryosat-2 v2.1 setting in August

**System information (please complete the following information):**
 - pysiral v0.6.4 master

**Additional context**

```
Traceback (most recent call last):                                                                                                   
  File "C:\python\Anaconda2\envs\pysiral-production\Scripts\\pysiral-l2proc.py", line 293, in <module>                               
    pysiral_l2proc()                                                                                                                 
  File "C:\python\Anaconda2\envs\pysiral-production\Scripts\\pysiral-l2proc.py", line 37, in pysiral_l2proc                          
    pysiral_l2proc_time_range_job(args)                                                                                              
  File "C:\python\Anaconda2\envs\pysiral-production\Scripts\\pysiral-l2proc.py", line 84, in pysiral_l2proc_time_range_job           
    l2proc.process_l1b_files(l1b_files)                                                                                              
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\l2proc.py", line 119, in process_l1b_files             
    self.run()                                                                                                                       
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\l2proc.py", line 123, in run                           
    self._l2_processing_of_orbit_files()                                                                                             
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\l2proc.py", line 250, in _l2_processing_of_orbit_files 
    error_status, error_codes = self._get_auxiliary_data(l2)                                                                         
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\l2proc.py", line 354, in _get_auxiliary_data           
    auxclass.add_variables_to_l2(l2)                                                                                                 
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\auxdata\__init__.py", line 103, in add_variables_to_l2 
    self.get_l2_track_vars(l2)                                                                                                       
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\auxdata\snow.py", line 247, in get_l2_track_vars       
    self.update_external_data()                                                                                                      
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\auxdata\__init__.py", line 141, in update_external_data
    self.load_requested_auxdata()                                                                                                    
  File "C:\python\Anaconda2\envs\pysiral-production\lib\site-packages\pysiral\auxdata\snow.py", line 271, in load_requested_auxdata  
    self.add_handler_message()                                                                                                       
TypeError: add_handler_message() takes exactly 2 arguments (1 given)                                                                 
```

**Comment by shendric** [comment]
should be fixed in a0473d1
