### ISSUE TITLE
L2 processor: W99 attribute

### ISSUE THREAD

**Issue by amguillot** [shendric/pysiral#2]
Traceback (most recent call last):
  File "bin/pysiral-l2proc.py", line 296, in <module>
    pysiral_l2proc()
  File "bin/pysiral-l2proc.py", line 37, in pysiral_l2proc
    pysiral_l2proc_time_range_job(args)
  File "bin/pysiral-l2proc.py", line 86, in pysiral_l2proc_time_range_job
    l2proc.process_l1b_files(l1b_files)
  File "../pysiral/pysiral/l2proc.py", line 152, in process_l1b_files
    self.run()
  File "../pysiral/pysiral/l2proc.py", line 156, in run
    self._l2_processing_of_orbit_files()
  File "../pysiral/pysiral/l2proc.py", line 370, in _l2_processing_of_orbit_files
    error_status, error_codes = self._get_snow_parameters(l2)
  File "../pysiral/pysiral/l2proc.py", line 611, in _get_snow_parameters
    snow, msg = self._snow.get_along_track_snow(l2)
  File "../pysiral/pysiral/snow.py", line 25, in get_along_track_snow
    snow, msg = self._get_along_track_snow(l2)
  File "../pysiral/pysiral/snow.py", line 121, in _get_along_track_snow
    snow = self._get_warren99_fit(l2)
  File "../pysiral/pysiral/snow.py", line 160, in _get_warren99_fit
    l2x, l2y = self._p(l2.track.longitude, l2.track.latitude)
AttributeError: 'Warren99' object has no attribute '_p'

Warren99 has an attribute named "p" but not "_p" @shendric

**Comment by shendric** [comment]
should be fixed in 4e902d2
