### ISSUE TITLE
Refactor handling of errors and exceptions

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#84]
The current `error` module was added to provide clean feedback and also be able to count errors, e.g. if an error should not raise an exception. But instead of raising an exception, the current implementation uses a simple `sys.exit(1)` statement (https://github.com/shendric/pysiral/blob/87723d073a3d080941028874fa1a3fb691befdf2/pysiral/errorhandler.py#L55) and a set of deprecated error codes. 

This approach however is difficult to test or trouble shoot and the current approach should be replaced by custom python exceptions, which should display pysiral configuration settings to be able to trouble shoot quickly based on exception type. 

Potential candidates for pysiral exceptions: 

- [ ] `PysiralConfigError`
- [ ] `PysiralInputError`
- [ ] `PysiralOutputError`
- ...

More errors are to be defined.

**Comment by shendric** [comment]
Example of how pysiral exceptions could be added: 

```python
# Test Custom Exception.

import pysiral


class PysiralException(Exception):
    """ Still an exception raised when uncommon things happen """
    def __init__(self, message, payload=None):
        self.message = message
        self.payload = payload

    def __str__(self):
        return str(f"\npysiral version: {pysiral.version}\n{self.message}")


def func_with_error() -> None:
    try:
        a = "1" + 2
    except TypeError as e:
        raise PysiralException("Custom error message") from e


func_with_error()
```

results in: 

```
Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Roaming\JetBrains\PyCharmCE2023.3\scratches\scratch_108.py", line 18, in func_with_error
    a = "1" + 2
TypeError: can only concatenate str (not "int") to str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\stefa\AppData\Roaming\JetBrains\PyCharmCE2023.3\scratches\scratch_108.py", line 23, in <module>
    func_with_error()
  File "C:\Users\stefa\AppData\Roaming\JetBrains\PyCharmCE2023.3\scratches\scratch_108.py", line 20, in func_with_error
    raise PysiralException("Custom error message") from e
__main__.PysiralException: 
pysiral version: 0.10
Custom error message
```
